---
- name: user module demo
  hosts: all
  become_user: root
  vars:
    myuser: "yaytemur"
    mypassword: "e3&@UQoaEz$APy"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"
