## USER-NAME,PASSWORD değişkendir.
---
- name: user module demo
  hosts: all
  become: true
  vars:
    myuser: "suprdops"
    mypassword: "7R$@W6%6JYyd9"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"
