---
- name: user module demo
  hosts: all
  become_user: root
  vars:
    myuser: "suprdops"
    mypassword: "B*w6u4ho3L2i@"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"
