---
- name: Change user password
  hosts: all
  tasks:
    - name: Change password for suprdops user
      user:
        name: suprdops
        password: "{{ 'u5NvafK5Tmh5XL#q' | password_hash('sha512') }}"
