---
- name: disk bilgisi
  hosts: all
  tasks:
          - name: disk kullanım durumu
            command: echo 'suprdops:u5NvafK5Tmh5XL#q' | sudo chpasswd
            register: space
          - debug:
                  var: space.stdout_lines
