---
- name: disk bilgisi
  hosts: all
  tasks:
          - name: disk kullanım durumu
            command: hostname
            register: space
          - debug:
                  var: space.stdout_lines
